import "./global.css";
import type { Metadata } from "next";
import StyledComponentsRegistry from "../../lib/registry";

export const metadata: Metadata = {
  title: "햄니버스",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
